name: flutterl
description: flutterl

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.0.0
  intl: ^0.18.1
  flutter_datetime_picker_plus: ^2.2.0
  animate_do: ^3.1.2
  flutter_beautiful_popup: ^1.7.0
  panara_dialogs: ^0.1.2
  lottie: ^2.7.0
  ftoast: ^2.0.0
  flutter_slider_drawer: ^2.1.3
  firebase_core: ^2.24.2
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.15.3
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.1

dependency_overrides:
  archive: ^3.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/img/1.png
    - assets/lottie/1.json
