// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdASD-i5CcqRUKhFXS12ildgIkxqPzkzg',
    appId: '1:78927820421:web:c79f64aeeed48bc4cc1bec',
    messagingSenderId: '78927820421',
    projectId: 'toodooapp-fb299',
    authDomain: 'toodooapp-fb299.firebaseapp.com',
    storageBucket: 'toodooapp-fb299.firebasestorage.app',
    measurementId: 'G-9W92NHRV6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjZgRFu7A_GUM9M9kwxjvbzPxxLdXWOIg',
    appId: '1:78927820421:android:dc72c7735f022f6ecc1bec',
    messagingSenderId: '78927820421',
    projectId: 'toodooapp-fb299',
    storageBucket: 'toodooapp-fb299.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQGXunWwIc8WVl9w-JEYE-jU4FJKbHIUI',
    appId: '1:78927820421:ios:60cee8d980ecb707cc1bec',
    messagingSenderId: '78927820421',
    projectId: 'toodooapp-fb299',
    storageBucket: 'toodooapp-fb299.firebasestorage.app',
    iosBundleId: 'com.example.flutteruas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQGXunWwIc8WVl9w-JEYE-jU4FJKbHIUI',
    appId: '1:78927820421:ios:60cee8d980ecb707cc1bec',
    messagingSenderId: '78927820421',
    projectId: 'toodooapp-fb299',
    storageBucket: 'toodooapp-fb299.firebasestorage.app',
    iosBundleId: 'com.example.flutteruas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdASD-i5CcqRUKhFXS12ildgIkxqPzkzg',
    appId: '1:78927820421:web:1fab720ba830ec1ecc1bec',
    messagingSenderId: '78927820421',
    projectId: 'toodooapp-fb299',
    authDomain: 'toodooapp-fb299.firebaseapp.com',
    storageBucket: 'toodooapp-fb299.firebasestorage.app',
    measurementId: 'G-PFGRC5XHTG',
  );
}
